# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_NT_FS_PERSONALITY_KUNIT_TEST) += ntpers_kunit.o

ntpers_kunit-y := path_kunit.o volume_kunit.o casefold_kunit.o meta_kunit.o \
		  resolve_kunit.o open_kunit.o handle_kunit.o
